language: rust

rust:
- stable
- nightly

os:
- linux
- osx
- windows

stages:
- check
- test
- sanitize

addons:
  apt:
    packages:
      - libssl-dev

jobs:
  include:
  - name: fmt
    stage: check
    rust: stable
    os: linux
    install:
    - rustup component add rustfmt
    script:
    - cargo fmt --all -- --check

  - name: clippy
    stage: check
    rust: stable
    os: linux
    install:
    - rustup component add clippy
    script:
    - cargo clippy --all-targets -- -D warnings

  - name: coverage
    stage: check
    rust: nightly
    os: linux
    install:
    - cargo +nightly install cargo-tarpaulin
    script:
    - travis_retry cargo +nightly tarpaulin -v --all-features --out Xml
    after_success:
    - bash <(curl -s https://codecov.io/bash)

  - name: doc
    stage: check
    rust: nightly
    os: linux
    script:
    - cargo +nightly doc --all-features

  - name: address
    stage: sanitize
    rust: nightly
    os: linux
    script:
    - RUSTFLAGS="-Z sanitizer=address" cargo test --tests --lib -v --all-features --target x86_64-unknown-linux-gnu

  - name: leak
    stage: sanitize
    rust: nightly
    os: linux
    script:
    - RUSTFLAGS="-Z sanitizer=leak" cargo test --tests --lib -v --all-features --target x86_64-unknown-linux-gnu
